# Generated by Django 3.2.4 on 2021-06-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido Cliente')),
                ('nom_usuario', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('num_telefonico', models.IntegerField(max_length=9, verbose_name='Numero de Telefono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electronico')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
